-keep class com.example.tweakly.data.model.** { *; }
-keep class com.google.firebase.** { *; }
-keep class com.google.android.gms.** { *; }
-keepattributes *Annotation*, SourceFile, LineNumberTable
-dontwarn okhttp3.**
-dontwarn retrofit2.**
-dontwarn kotlinx.serialization.**
-keep class kotlinx.serialization.** { *; }
